### PR TITLE
pkg/sanity: support sanity testing in another Ginkgo suite

### PR DESCRIPTION
**Pull request by pohly**
This was not possible before:
- Ginkgo only supports one set of Before/AfterSuite calls,
  which might be in use already in the existing suite (for
  example, the Kubernetes e2e framework).
- When nesting the sanity test inside a Ginkgo spec there
  is no testing.T pointer that could be passed to
  the Test method.

Now all global variables are replaced with a test context that gets
passed into the specs explicitly. For this to work, specs must be set
up with SanityDescribe instead of the previous Describe call.

The Test and Config API are unchanged, but there is one slight change
of behavior: previously it was possible to define two tests with
different configs in the same test binary and then running each test
would execute the sanity tests for that config. That no longer works
because running one test changes the global Ginkgo suite and running
the second test would then also run the specs from the first one.

This usage could be supported by having one test function which takes
multiple configs, then runs one suite that contains tests for all of
them.

Probably it is easier to just use a Ginkgo suite, because there
multiple different configs can be handled already normally via
different Describe specs: calling the new GinkgoTest API will add all
sanity test cases for one configuration to the spec in which the API
is called.

### CODE REVIEW

**Comment by lpabon** [comment]
Hi @pohly , this vet and unit test issues.

**Comment by pohly** [comment]
Ah, those are in .travis.yml. I was looking for a "make check" or "make test" and missed the .travis.yml. I'll fix these issues.

**Comment by pohly** [comment]
`make build` doesn't rebuild when the sources change. Should we make $(APP) a phony target to ensure that `go build` is always invoked?

**Comment by lpabon** [comment]
>make build doesn't rebuild when the sources change. Should we make $(APP) a phony target to ensure that go build is always invoked? And should the top-level Makefile also build the csi-sanity command? Currently one has to remember to invoke "make" in two different directories.

If you want to, please feel free to send a PR for this.

**Comment by pohly** [comment]
Luis Pabón <notifications@github.com> writes:

>>make build doesn't rebuild when the sources change. Should we make $(APP) a phony target to ensure that go build is always invoked? And should the top-level Makefile also build the csi-sanity command? Currently one has to remember to invoke "make" in two different directories.
>
> If you want to, please feel free to send a PR for this.

@lpabon I ended up adding this to my pending PR #93 because I wanted to
simplify testing that while I worked on it, please see
https://github.com/kubernetes-csi/csi-test/pull/93/commits/e2e872d7fb9497e2f83089cc50cad379b98487af.

**Pull request merged**
