### PR TITLE
Fix markdown issue in README

### PR DESCRIPTION
**Pull request by Madhu-1**

### CODE REVIEW

**Comment by pohly** [comment]
Why is this needed? I cannot see a difference in the rendered HTML page on Github with and without this change.

**Comment by Madhu-1** [comment]
@pohly it fixes the markdown style issues found with the static tool `mdl`

**Comment by pohly** [comment]
Okay. Next time, please put such information into the commit messages, it makes it simpler to review changes.

/lgtm
/approve

**Pull request merged**
