### PR TITLE
Update to v1.0.0-RC2 of CSI

### PR DESCRIPTION
**Pull request by lpabon**
Signed-off-by: Luis Pabón <lpabon@gmail.com>

### CODE REVIEW

**Comment by lpabon** [comment]
need to update old examples also.. Working on that now..

**Comment by davidz627** [comment]
Sanity and Vendor changes LGTM

**Comment by msau42** [comment]
lgtm, could you separate vendor and non-vendor into different commits?

**Comment by pohly** [comment]
With this PR merged and v1.0.0-rc2 released, should https://github.com/kubernetes-csi/csi-test/issues/137 get closed as "won't fix" because everyone has to move to CSI 1.0.0 now anyway?

What CSI driver developers who still need to support older Kubernetes releases? Does a CSI 1.0 driver work on, say, Kubernetes 1.11?

**Comment by msau42** [comment]
CSI in Kubernetes 1.13 is not compatible with 1.12.  Drivers need to update to the 1.0  spec to work on 1.13.  We should still support older releases of Kubernetes that use the older CSI spec.

**Pull request merged**
