### PR TITLE
Update README for sanity test using Ginkgo.

### PR DESCRIPTION
**Pull request by leakingtapan**
The original sample is using BeforeEach/AfterEach in a problematic way.

### CODE REVIEW

**Comment by pohly** [comment]
I still don't like mixing different things in the same commit ;-} Here that's the .gitignore update and the README.md update. Both make sense to me, though, so thanks for the PR.

**Comment by leakingtapan** [comment]
@pohly How about I split into two commits but reuse the same pr?

**Comment by pohly** [comment]
Cheng Pan <notifications@github.com> writes:
> @pohly How about I split into two commits but reuse the same pr?

That's fine with me.

**Comment by leakingtapan** [comment]
@pohly change is made

**Pull request merged**
