### PR TITLE
Donate csi-test to the CNCF/Kubernetes foundation

### PR DESCRIPTION
**Pull request by lpabon**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update the copyright from 4 years ago and donate to the CNCF/Kubernetes foundation

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
As discussed on Slack, it would be good to also get clarification on those files which have no copyright remark. `release-tools/verify-boilerplate.sh` reports all issues.

**Comment by pohly** [comment]
LGTM

I'll fix the headers for pkg/sanity/resources.go and pkg/sanity/tests.go ("Copyright 2018 Intel Corporation" - wow, that feels like ages ago) in a separate PR.

/assign @msau42

for the final merging.

**Comment by msau42** [comment]
/approve
Thanks!

**Comment by msau42** [comment]
/approve
Thanks!

**Pull request merged**
