### PR TITLE
Prow update master

### PR DESCRIPTION
**Pull request by TerryHowe**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Update release-tools according to https://github.com/kubernetes-csi/csi-release-tools/issues/7

**Which issue(s) this PR fixes**:
Related https://github.com/kubernetes-csi/csi-release-tools/pull/259

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by TerryHowe** [comment]
Can I get an /ok-to-test ?

**Comment by TerryHowe** [comment]
Once the tests run, I'll know if I neded the go.mod change like I was attempting in https://github.com/kubernetes-csi/csi-test/pull/560

The only other PR that might be related is https://github.com/kubernetes-csi/csi-driver-host-path/pull/570

**Comment by jsafrane** [comment]
I addition, can you please use the current master of release-tools? We have go 1.23.1 there already.

**Comment by TerryHowe** [comment]
> go mod tidy && go mod vendor

Done

**Pull request merged**
