### PR TITLE
sanity: capture newly created volume IDs

### PR DESCRIPTION
**Pull request by avalluri**
In one of ListVolumes tests, newly created volume ids were not captured. Though the test has needed cleaning up code, it was affected because of the empty newVolIDs array. This leads to leaking of volumes.

 /kind bug

### CODE REVIEW

**Comment by pohly** [comment]
Thanks for highlighting this issue. However, the issue is even more severe: if one of the asserts fails after creating the volume, the cleanup code won't get executed. I missed that when merging https://github.com/kubernetes-csi/csi-test/pull/80.

Can you change the test such that it uses https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/cleanup.go?

**Comment by avalluri** [comment]
> Thanks for highlighting this issue. However, the issue is even more severe: if one of the asserts fails after creating the volume, the cleanup code won't get executed. I missed that when merging #80.
> Can you change the test such that it uses https://github.com/kubernetes-csi/csi-test/blob/master/pkg/sanity/cleanup.go?

@pohly, I updated the PR to use Cleanup interface as you suggested.

**Pull request merged**
