### PR TITLE
Bump go version to 1.15

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Updated go version to 1.15
```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/approve
/hold
Can you add a release note?

**Comment by humblec** [comment]
@msau42 shall we add release note saying we updated the go version to 1.15 ? or any other suggestions?

**Comment by msau42** [comment]
Yes that sounds good

**Comment by humblec** [comment]
> Yes that sounds good

@msau42 added, ptal :+1:

**Pull request merged**
