### PR TITLE
update .gitignore

### PR DESCRIPTION
**Pull request by Madhu-1**
updated .gitignore file to discard IDE specific files.

### CODE REVIEW

**Comment by Madhu-1** [comment]
@pohly I see in other kubernetes-CSI repo the gitignore has tool-specific ignore rules https://github.com/kubernetes-csi/external-snapshotter/blob/master/.gitignore
https://github.com/kubernetes-csi/external-attacher/blob/master/.gitignore

**Comment by pohly** [comment]
Yes. We need to decide which way we want to go and then make sure all repos are in sync.

I've put it on the agenda for today's CSI team standup meeting.

**Comment by pohly** [comment]
The agreement in the meeting was to limit `.gitignore` to just the parts that are specific to the project.

Can you update the PR such that only the following lines are left?
```
bin/mock
cmd/csi-sanity/csi-sanity
```

**Comment by Madhu-1** [comment]
@pohly done PTAL

**Pull request merged**
