### PR TITLE
avoid close of closed conn when the controller address of config is empty

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

avoid close of closed conn when the controller address of config is empty

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
> avoid close of closed conn when the controller address of config is empty

Was that actually causing problems? I'm just curious.

**Comment by carlory** [comment]
It is not clear at present, I just discovered this phenomenon in the process of reading the code

**Pull request merged**
