### PR TITLE
chore: update go version to fix tests

### PR DESCRIPTION
**Pull request by TerryHowe**
**What type of PR is this?**

/kind failing-test

csi-release-test failing tests

**What this PR does / why we need it**:
Should fix
https://github.com/kubernetes-csi/csi-release-tools/pull/259

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

May require:
https://github.com/kubernetes-csi/csi-release-tools/pull/260

**Does this PR introduce a user-facing change?**:
No

```release-note
NONE
```

### CODE REVIEW

**Comment by stmcginnis** [comment]
@xing-yang would you be able to help with an ok-to-test here? :)

**Comment by stmcginnis** [comment]
Hmm, looks like the prow jobs are still running with Go 1.19, this failing with the newer directive:

> /home/prow/go/src/github.com/kubernetes-csi/csi-test/go.mod:5: unknown directive: toolchain

**Comment by stmcginnis** [comment]
The repo's version of release-tools is out of date.

Current release-tools points to Go 1.22.5. https://github.com/kubernetes-csi/csi-release-tools/blob/master/prow.sh#L89

Local copy still points to an older version using 1.19: https://github.com/kubernetes-csi/csi-test/blob/master/release-tools/prow.sh#L89

**Comment by TerryHowe** [comment]
> The repo's version of release-tools is out of date.

Fixed

**Comment by stmcginnis** [comment]
I think we'll need a full update like #431.

It's an unfortunate circular dependency between the tools used to test and the tools used to release. :/

**Comment by TerryHowe** [comment]
I'll take a look at it later and see if I can make sense of it.

**Comment by TerryHowe** [comment]
* Changed this PR to 1.22 like https://github.com/kubernetes-csi/csi-release-tools/blob/master/prow.sh#L89
* Updated go version for csi-driver-host-path https://github.com/kubernetes-csi/csi-driver-host-path/pull/568/files

**Comment by TerryHowe** [comment]
I think this will be depent upon
* https://github.com/kubernetes-csi/csi-test/pull/561/
* https://github.com/kubernetes-csi/csi-driver-host-path/pull/570 (maybe)

**Comment by TerryHowe** [comment]
* I think https://github.com/kubernetes-csi/csi-test/pull/561 is the correct approach

**Pull request closed without merging**
