### PR TITLE
Add changelog for v4.0.0

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR adds changelog for v4.0.0.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@pohly should the next release version be v3.2.0?  We updated the CSI spec to v1.3.0.

**Review by pohly — CHANGES_REQUESTED** [review]
The next release needs to be 4.0.0 because of the API change in https://github.com/kubernetes-csi/csi-test/pull/261

The module version was bumped in https://github.com/kubernetes-csi/csi-test/pull/261/commits/f7260c77af5f34654f9cc4687f43429cc2b153c1

**Comment by xing-yang** [comment]
Got it.  Thanks @pohly.

**Comment by xing-yang** [comment]
@pohly Addressed your comment.  PTAL.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
