### PR TITLE
Advertise SINGLE_NODE_MULTI_WRITER capability

### PR DESCRIPTION
**Pull request by chrishenzie**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR allows the mock driver to advertise the `SINGLE_NODE_MULTI_WRITER` capability and accept the `SINGLE_NODE_SINGLE_WRITER` and `SINGLE_NODE_MULTI_WRITER` access modes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @msau42 
/assign @jingxu97

### CODE REVIEW

**Comment by chrishenzie** [comment]
This PR is ready for review now that the CSI spec has been released.

**Comment by xing-yang** [comment]
Can you remove the special notes as you don't need that now?  I don't think this needs a release note.  Can you remove it?

**Comment by chrishenzie** [comment]
@xing-yang Done

**Comment by msau42** [comment]
I believe we're moving away from mock driver and using hostpath driver instead.

**Comment by pohly** [comment]
The deprecation was announced in https://github.com/kubernetes-csi/csi-test/releases/tag/v4.2.0

We don't have a regular release schedule for csi-test. Shall I remove the source code from master now and then do a 5.0.0 immediately or wait, say, half a year (= October)?

I'm undecided about the version. The remaining code is mostly unchanged compared to 4.2.0.

**Pull request merged**
